#!/bin/bash

# Custom Rofi Script

BORDER="#191919"
SEPARATOR="#191919"
FOREGROUND="#FFFFFF"
BACKGROUND="#191919"
BACKGROUND_ALT="#252525"
HIGHLIGHT_BACKGROUND="#039be5"
HIGHLIGHT_FOREGROUND="#191919"

BLACK="#000000"
WHITE="#ffffff"
RED="#e53935"
GREEN="#43a047"
YELLOW="#fdd835"
BLUE="#1e88e5"
MAGENTA="#00897b"
CYAN="#00acc1"
PINK="#d81b60"
PURPLE="#8e24aa"
INDIGO="#3949ab"
TEAL="#00897b"
LIME="#c0ca33"
AMBER="#ffb300"
ORANGE="#fb8c00"
BROWN="#6d4c41"
GREY="#757575"
BLUE_GREY="#546e7a"
DEEP_PURPLE="#5e35b1"
DEEP_ORANGE="#f4511e"
LIGHT_BLUE="#039be5"
LIGHT_GREEN="#7cb342"

# Launch Rofi
rofi -no-lazy-grab -show window \
-display-window "Overview :" -drun-display-format "{name}" \
-hide-scrollbar true \
-bw 0 \
-lines 1 \
-line-padding 20 \
-padding 60 \
-width 70 \
-columns 10 \
-show-icons -icon-theme "Tela" \
-font "Fira Sans Mono 12" \
-color-enabled true \
-kb-cancel "Alt+Escape,Escape" \
-kb-accept-entry "!Alt-Tab,!Alt+Alt_L" \
-kb-row-down "Alt+Tab,Alt+Down" \
-kb-row-up "Alt+ISO_Left_Tab,Alt+Up" \
-selected-row 1 \
-window-format {t} \
-color-window "$BACKGROUND,$BORDER,$SEPARATOR" \
-color-normal "$BACKGROUND_ALT,$FOREGROUND,$BACKGROUND_ALT,$HIGHLIGHT_BACKGROUND,$HIGHLIGHT_FOREGROUND" \
-color-active "$BACKGROUND,$MAGENTA,$BACKGROUND_ALT,$HIGHLIGHT_BACKGROUND,$HIGHLIGHT_FOREGROUND" \
-color-urgent "$BACKGROUND,$YELLOW,$BACKGROUND_ALT,$HIGHLIGHT_BACKGROUND,$HIGHLIGHT_FOREGROUND"

# More Options
# -fullscreen \

# Theming help
# color window = background, border, separator
# color normal = background, foreground, background-alt, highlight-background, highlight-foreground
# color active = background, foreground, background-alt, highlight-background, highlight-foreground
# color urgent = background, foreground, background-alt, highlight-background, highlight-foreground
