#!/bin/sh

active_window=$(xprop -root _NET_ACTIVE_WINDOW|cut -d ' ' -f 5|sed -e 's/../0&/2')
current_display=$(wmctrl -d|grep "*"|awk '{print $1}')

color1="039be5" # Blue

active_window_decoration_style_left_side="%{F#$color1}%{+u}%{u#$color1}"
active_window_decoration_style_right_side="%{-u}%{F-}"
first=0

current_windows=$(wmctrl -lx|awk \
					-v current_display="$current_display" \
					-v active_window="$active_window" \
					-v active_window_decoration_style_left_side="$active_window_decoration_style_left_side" \
					-v active_window_decoration_style_right_side="$active_window_decoration_style_right_side" '

	{
		if ($2==current_display) {

			split($5,window_title,".")

			if ($1==active_window) {

				window_title[1]=active_window_decoration_style_left_side window_title[1] active_window_decoration_style_right_side

			}

			if (first == 0) {

				print "%{A1: wmctrl -ia "$1" & disown:}"window_title[1]"%{A}"
				first=1

			} else {

				print " · %{A1: wmctrl -ia "$1" & disown:}"window_title[1]"%{A}"

			}
		}

	}')
#
# Decorated version END
#######################

echo $current_windows
